name: Build App

permissions:
  contents: write

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Create builds folder
        run: rm -rf builds && mkdir builds


      - name: Build DMG
        run: |
          echo "Listing target directory..."
          ls -l target

          JAR=$(ls target/*.jar | grep -v original | head -n 1)
          if [ -z "$JAR" ]; then
            echo "ERROR: No valid JAR found"
            exit 1
          fi

          JAR_NAME=$(basename "$JAR")
          echo "Using JAR: $JAR_NAME"

          jpackage \
            --input target \
            --dest builds \
            --name MarsTravelsBooking \
            --app-version 1.0.0 \
            --main-jar "$JAR_NAME" \
            --main-class com.example.grupp2_system.App.Launcher \
            --type dmg \
            --icon icons/icon.icns \
            --verbose

          echo "Build result:"
          ls -l builds

          xattr -cr builds/*.dmg || true

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: builds/*.dmg


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: MarsTravelsBooking v1.0.${{ github.run_number }}
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}