name: Build App

permissions:
  contents: write

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create builds folder
        run: |
          rm -rf builds
          mkdir builds

      - name: Build DMG
        run: |
          jpackage \
          --input out/artifacts/grupp2_system_jar \
          --dest builds \
          --name MarsTravelsBooking \
          --app-version 1.0.0 \
          --main-jar grupp2_system.jar \
          --main-class com.example.grupp2_system.App.Launcher \
          --type dmg \
          --icon icons/icon.icns

          xattr -cr builds

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: builds/*.dmg

  build-windows:
    runs-on: windows-latest
    needs: build-mac

    steps:
      - uses: actions/checkout@v4

      - name: Create builds folder
        run: |
          rmdir /s /q builds || true
          mkdir builds

      - name: Build EXE
        run: |
          jpackage ^
          --input out/artifacts/grupp2_system_jar ^
          --dest builds ^
          --name MarsTravelsBooking ^
          --app-version 1.0.0 ^
          --main-jar grupp2_system.jar ^
          --main-class com.example.grupp2_system.App.Launcher ^
          --type exe ^
          --icon icons/icon.ico ^
          --win-menu ^
          --win-shortcut ^
          --win-dir-chooser

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: builds/*

      - name: Download Mac artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: builds

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: MarsTravelsBooking v1.0.${{ github.run_number }}
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}